dist: bionic
language: php
sudo: false

php:
  - 8.1

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - DRUPAL=10.1
    - DRUPAL=10.2

jobs:
  fast_finish: true

before_install:
  # Update & configure composer.
  - composer self-update --2
  - composer --version
  - if [ "${GITHUB_TOKEN}" != "" ]; then composer config github-oauth.github.com ${GITHUB_TOKEN}; fi
  - if [ "${REPMAN_TOKEN}" != "" ]; then composer config --global --auth http-basic.digipolis.repo.repman.io token ${REPMAN_TOKEN}; fi

  # Get the CodeClimate test reporter.
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

  # Require Proper Drupal core version.
  - composer require -n --no-update --sort-packages --dev drupal/core:~$DRUPAL.0

install:
  - composer install -n

script:
  # Checks to be added to the list below: phpstan
  # Until Flexmail is not used with patches, phpstan can't be run because will
  # not take into account the patch changes.
  - vendor/bin/grumphp run -n --tasks=composer,composer_normalize,git_blacklist,git_branch_name,phpcpd,phpcs,phpmd,phpunit,twigcs,yamllint,securitychecker_enlightn

after_script:
  # Run the Code Climate test reporter.
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT
