<?php

/**
 * @file
 * Implemented hooks.
 */

declare(strict_types=1);

/**
 * Implements hook_theme().
 */
function dg_cookiebot_theme() {
  return [
    'dg_cookiebot_settings_link' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_preprocess_video_embed_iframe().
 *
 * Adds the proper <code>data-cookieconsent</code> attribute to the
 * video_embed_iframe template when privacy option is enabled.
 */
function dg_cookiebot_preprocess_video_embed_iframe(&$variables): void {
  $config = \Drupal::configFactory()->get('video_embed_field.settings');
  if ($config->get('privacy_mode') !== 'enabled') {
    return;
  }

  /** @var \Drupal\Core\Template\Attribute $attributes */
  $attributes = &$variables['attributes'];
  $attributes->setAttribute('data-cookieconsent', 'necessary');
}
